import json


# prompt block
PROMPT_BLOCK_DEFAULT_CODE = 0

# input block
INPUT_BLOCK_DEFAULT_CODE = 0
INPUT_BLOCK_SELF_CODE = -1

# flag action
FLAG_START_SKILL = 1
FLAG_CANCEL_SKILL = 2
FLAG_SWITCH_CHANNEL = 3
