# Generated by Django 3.0.4 on 2021-05-06 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bigbot', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsephrase',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Attachment'),
        ),
        migrations.AddField(
            model_name='responsephrase',
            name='delegate_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.BotDelegate'),
        ),
        migrations.AddField(
            model_name='inputpattern',
            name='delegate_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.BotDelegate'),
        ),
        migrations.AddField(
            model_name='inputpattern',
            name='response_ids',
            field=models.ManyToManyField(to='bigbot.ResponsePhrase'),
        ),
    ]
